### PR TITLE
added more suffix fields

### PR DESCRIPTION
**Pull request by sarath-yerra**

### CODE REVIEW

**Comment by sarath-yerra** [comment]
Screen Shot 2020-10-22 at 3 44 49 PM

**Review by maheshkurma — CHANGES_REQUESTED** [review]
@sarath-yerra  The order of the options should follow: Sr, Jr, I, II, III, IV, V, VI.

**Review by pantrytrak-core — CHANGES_REQUESTED** [review]
Could you please tweak the values for JR and SR so that both the label and the value are in upper case. That will match up to how we display and store them on the PantryTrak side.  Thanks,

image

**Comment by sarath-yerra** [comment]
Screen Shot 2020-10-23 at 9 46 31 AM

**Comment by sarath-yerra** [comment]
Yes Made Changes as per PantryTrak

**Comment by sarath-yerra** [comment]
Screen Shot 2020-10-23 at 9 51 31 AM

**Review by pantrytrak-core — APPROVED** [review]
looks good

**Review by maheshkurma — APPROVED** [review]

**Pull request merged**
