### PR TITLE
Added Error Component

### PR DESCRIPTION
**Pull request by maheshkurma**
Added Error Component-
First commit - handles 404 error and shows an error page.
Handles & Show event date validation error messages in UI (example: event expiration, capacity .....)

### CODE REVIEW

**Comment by maheshkurma** [comment]
Screen Shot 2020-09-10 at 8 33 06 PM

**Comment by maheshkurma** [comment]
Screen Shot 2020-09-15 at 11 39 17 AM

**Comment by sarath-yerra** [comment]
+1

**Comment by sarath-yerra** [comment]
All the changes looks good.

**Review by sarath-yerra — APPROVED** [review]

**Pull request merged**
