### PR TITLE
fix for guest user returning to home

### PR DESCRIPTION
**Pull request by sarath-yerra**

### CODE REVIEW

**Comment by sarath-yerra** [comment]
Screen Shot 2020-11-13 at 2 35 49 PM

**Comment by sarath-yerra** [comment]
Screen Shot 2020-11-13 at 2 36 02 PM

**Comment by sarath-yerra** [comment]
Fixed issues related to Guest Home redirecting issue @maheshkurma @pantrytrak-core

**Comment by sarath-yerra** [comment]
Screen Shot 2020-11-13 at 2 41 28 PM
Screen Shot 2020-11-13 at 2 41 14 PM
Screen Shot 2020-11-13 at 2 40 56 PM

**Review by maheshkurma — APPROVED** [review]

**Pull request merged**
