### PR TITLE
Ft 16.1 registration address search

### PR DESCRIPTION
**Pull request by Basiltj07**
This pull request contain the fix for issue #51

### CODE REVIEW

**Comment by maheshkurma** [comment]
Trying to test in local dev in this branch(PR)
seems like all address inputs are not auto-filling(only address_line_1 & state inputs are filled), after choosing suggested address.

step-1 :
Screen Shot 2020-07-02 at 5 24 43 PM

step-2 :
Screen Shot 2020-07-02 at 5 25 02 PM

**Comment by ashikvarma11** [comment]
@maheshkurma  I couldn't reproduce the issue. Tested it out again and got this result:
Screenshot from 2020-07-04 10-55-31
Screenshot from 2020-07-04 10-55-55

**Comment by ashikvarma11** [comment]
@davidpickering @maheshkurma Fixes are made in the PR #58 .

**Comment by davidpickering** [comment]
> 
> 
> @davidpickering @maheshkurma Fixes are made in the PR #58 . The data was populating in the fields but somehow, React was not recognizing the change. So I had to add `onChange` attribute and explicitly set the data when changed.

Thanks @ashikvarma11 . Does this mean we should close this PR in favor of PR58?

**Comment by ashikvarma11** [comment]
Yes. Thats correct.

**Pull request closed without merging**
