### PR TITLE
Added other in the gender

### PR DESCRIPTION
**Pull request by sarath-yerra**

### CODE REVIEW

**Comment by thompson2091** [comment]
I have confirmed that adding an "other" option to the gender dropdown is not going to impact PantryTrak.  This is good to merge into master from that perspective.

**Review by pantrytrak-core — APPROVED** [review]
looks great, thanks for the quick turnaround on this.

**Review by pantrytrak-core — CHANGES_REQUESTED** [review]
I was checking the code here and it looks like the value for this select item is "female" and should be "other".

**Review by maheshkurma — APPROVED** [review]
looks good

**Comment by sarath-yerra** [comment]
Screen Shot 2020-10-23 at 1 59 52 PM

**Review by maheshkurma — APPROVED** [review]

**Review by pantrytrak-core — APPROVED** [review]
looks good

**Pull request merged**
