### PR TITLE
url change for analytics

### PR DESCRIPTION
**Pull request by sarath-yerra**

### CODE REVIEW

**Comment by maheshkurma** [comment]
Need to fix - Compiler Warnings on this PR.

**Comment by sarath-yerra** [comment]
Screen Shot 2020-09-21 at 9 52 47 AM
Screen Shot 2020-09-21 at 9 53 03 AM
Screen Shot 2020-09-21 at 9 55 13 AM

**Comment by sarath-yerra** [comment]
Screen Shot 2020-09-21 at 9 55 35 AM

**Review by maheshkurma — APPROVED** [review]
Updated registration process with unique URLs, such as:

/events/list
/events/details/:id
/events/register/:id
/events/confirm

**Comment by maheshkurma** [comment]
Google TagManager scripts are missing in this PR.

**Review by maheshkurma — APPROVED** [review]
looks good now,
updated Google TagManager scripts..

**Pull request merged**
