### PR TITLE
Ui fixes to list events

### PR DESCRIPTION
**Pull request by sarath-yerra**

### CODE REVIEW

**Comment by sarath-yerra** [comment]
Screen Shot 2020-10-20 at 4 27 35 PM

**Review by pantrytrak-core — APPROVED** [review]
Looks good from my perspective. Excited that we're getting closer on having the logged  in landing page.

**Comment by maheshkurma** [comment]
@sarath-yerra  resolve conflicts

**Comment by sarath-yerra** [comment]
Fixed

**Pull request merged**
