### PR TITLE
added twillio message and sending time and date for reserve time feat…

### PR DESCRIPTION
**Pull request by sarath-yerra**
…ure and updated text for RSVP feature

### CODE REVIEW

**Comment by sarath-yerra** [comment]
Screen Shot 2020-11-24 at 5 53 18 PM

**Comment by sarath-yerra** [comment]
Screen Shot 2020-11-20 at 11 20 49 AM

**Comment by sarath-yerra** [comment]
Screen Shot 2020-11-24 at 5 52 57 PM

**Comment by sarath-yerra** [comment]
Image from iOS

**Comment by sarath-yerra** [comment]
Image from iOS (1)

**Comment by sarath-yerra** [comment]
Added a Sample Screenshots for RSVP and Reserve Time Feature

**Review by maheshkurma — APPROVED** [review]
Include event time and date in text message for Registration confirmation(Reserve Time).
note: sms includes only Identification Code for RSVP.

approving this PR.

**Pull request merged**
