### PR TITLE
split registration process into two pages

### PR DESCRIPTION
**Pull request by maheshkurma**
First Commit - Split registration into two Pages, first page contains (Register Now, Save Time & business enforcement rules(todo)) and second page contains Actual registration form fields......

### CODE REVIEW

**Comment by maheshkurma** [comment]
Development In Progress.........

**Comment by sarath-yerra** [comment]
As this is a common branch still in WIP made this branch as Draft

**Comment by davidpickering** [comment]
@sarath-yerra & @maheshkurma thank you both for your hard work on this. Since you two co-authored, would you both please take a spin through the code, and either request changes or approve.

Reminder, the comment/request changes/approve controls are on the files tab 
image

Also, @seanlawrenz if you have some time and would be available to review this work we always welcome a 2nd opinion!

I'd also like to pull this up in someone's local dev environment and run through it.

**Comment by maheshkurma** [comment]
note: need to be clean up warnings...

**Comment by sarath-yerra** [comment]
@davidpickering Fixed issue related to Once the user comes after continuing as guest and try to do RSVP again
Fixed Bug:
scenario: When user lands on register page (user/authentications will get created), in middle if he comes back to home page and go through the registration process, fill the from and when u hit Register button, it is throwing error, need to fix this.

**Review by sarath-yerra — APPROVED** [review]

**Comment by sarath-yerra** [comment]
Tested all scenarios

**Pull request merged**
