### PR TITLE
stripping non-alphanumeric characters from form

### PR DESCRIPTION
**Pull request by sarath-yerra**

### CODE REVIEW

**Comment by sarath-yerra** [comment]
Screen Shot 2020-10-26 at 12 02 47 PM
Screen Shot 2020-10-26 at 12 03 05 PM

**Comment by sarath-yerra** [comment]
Screen Shot 2020-10-26 at 12 03 57 PM

**Comment by sarath-yerra** [comment]
1.Fixed issues related non-alphanumeric characters
2.Also Stripping spaces if there is a space before FN,MN,LN
3.Saving into DB After Stripping.
4.Showing on Confirm Page After Stripping.

**Comment by sarath-yerra** [comment]
Screen Shot 2020-10-26 at 10 02 39 PM
Screen Shot 2020-10-26 at 10 03 12 PM

**Comment by sarath-yerra** [comment]
Pushed a commit which allows Mark mentioned Special Characters 
ch`ray
ch'ray

**Comment by maheshkurma** [comment]
@sarath-yerra can you verify this once and confirm  - https://github.com/midohiofoodbank/freshtrak-client/issues/187#issuecomment-717479944

**Comment by sarath-yerra** [comment]
Screen Shot 2020-10-27 at 9 27 08 PM
Screen Shot 2020-10-27 at 9 26 52 PM

**Comment by sarath-yerra** [comment]
58	guest	2020-10-28 01:16:31.761732	2020-10-28 01:18:03.977620	cddcsscdscd '		cddcsscdscd '		male	3615221985	sarathpy.02@gmail.com	1234522 road  TX		losuible	AK	232&&&23		0	0	0	0	0	1991-02-14	qkyngb	NULL	NULL

**Review by maheshkurma — APPROVED** [review]

**Pull request merged**
