### PR TITLE
Show Event Details on Confirmation Page

### PR DESCRIPTION
**Pull request by sarath-yerra**

### CODE REVIEW

**Comment by sarath-yerra** [comment]
Screen Shot 2020-10-14 at 11 57 43 PM

**Comment by maheshkurma** [comment]
**Issue**: when u reload the page event details are missing on card.

Screen Shot 2020-10-15 at 5 18 38 PM

**Comment by sarath-yerra** [comment]
We are saving in redux thats the reason its not saving! This is a known issue. we can create a new issue for refresh

**Comment by maheshkurma** [comment]
i see sarath raised a new Issue https://github.com/midohiofoodbank/freshtrak-client/issues/176 to fix data missing on registration confirmation page

**Review by maheshkurma — APPROVED** [review]
approving & looks good for now.

**Pull request merged**
